In [1]:
import torch

In [2]:
torch.__version__

'1.9.0+cpu'

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
X = torch.from_numpy(arr)

In [9]:
type(X)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
# 2D numpy array

In [12]:
arr2d = np.arange(0.0,12.0)

In [13]:
arr2d = arr2d.reshape(4,3)

In [14]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
x2 = torch.from_numpy(arr2d)

In [16]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [18]:
X

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [19]:
# if do not want to affect the created tensor value from orginal numpy array
# for jot sharing smae memory

In [20]:
myarr = np.arange(0,10)
myarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(myarr)

In [22]:
my_other_tensor = torch.from_numpy(myarr)

In [23]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [24]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
myarr[0] = 99

In [26]:
myarr


array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [27]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_other_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [29]:
new_arr = np.array([1,2,3])

In [30]:
new_arr.dtype

dtype('int32')

In [31]:
tensor = torch.tensor(new_arr)

In [32]:
Tensor = torch.Tensor(new_arr)

In [33]:
tensor.dtype , Tensor.dtype

(torch.int32, torch.float32)

In [34]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [35]:
torch.empty(4,2)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [1.8754e+28, 5.1481e+22]])

In [36]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [37]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [38]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
torch.arange(0,9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
torch.arange(0,9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [41]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [42]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [43]:
# data type changes

In [44]:
my_tensor = torch.tensor([1,2,3])

In [45]:
my_tensor.dtype

torch.int64

In [46]:
my_tensor = my_tensor.type(torch.int32)

In [47]:
my_tensor.dtype

torch.int32

In [48]:
# tensor from random numbers

In [49]:
torch.rand(4,3)

tensor([[0.3991, 0.9525, 0.2644],
        [0.0676, 0.3907, 0.6701],
        [0.3514, 0.3445, 0.8621],
        [0.8441, 0.0078, 0.6351]])

In [50]:
torch.randn(4,3)

tensor([[-0.9597, -1.2769, -0.3222],
        [ 0.6701, -0.1856, -0.8318],
        [-0.9520, -0.3151, -1.0648],
        [-0.4324,  0.4685,  0.4801]])

In [51]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[3, 5, 7, 3, 2],
        [5, 8, 4, 8, 7],
        [9, 4, 8, 9, 0],
        [5, 9, 2, 5, 3],
        [1, 0, 8, 7, 0]])

In [52]:
x = torch.zeros(2,5)

In [53]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [54]:
x.shape

torch.Size([2, 5])

In [55]:
torch.rand_like(x)

tensor([[0.6665, 0.3703, 0.9799, 0.3377, 0.8544],
        [0.6196, 0.1743, 0.8217, 0.3696, 0.3616]])

In [56]:
torch.randint_like(x,low=0,high=11)

tensor([[ 2.,  4.,  5., 10.,  6.],
        [ 3.,  8., 10.,  0.,  5.]])

In [57]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [58]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])